# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'youtubedownloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(592, 467)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.downloadbord = QtWidgets.QGroupBox(self.centralwidget)
        self.downloadbord.setGeometry(QtCore.QRect(20, 10, 561, 61))
        self.downloadbord.setObjectName("downloadbord")
        self.download_lab = QtWidgets.QLineEdit(self.downloadbord)
        self.download_lab.setGeometry(QtCore.QRect(10, 20, 391, 31))
        self.download_lab.setObjectName("download_lab")
        self.download_btn = QtWidgets.QPushButton(self.downloadbord)
        self.download_btn.setGeometry(QtCore.QRect(420, 20, 121, 31))
        self.download_btn.setObjectName("download_btn")
        self.chnamebord = QtWidgets.QGroupBox(self.centralwidget)
        self.chnamebord.setGeometry(QtCore.QRect(20, 80, 561, 61))
        self.chnamebord.setObjectName("chnamebord")
        self.chname_lab = QtWidgets.QLineEdit(self.chnamebord)
        self.chname_lab.setGeometry(QtCore.QRect(10, 20, 391, 31))
        self.chname_lab.setObjectName("chname_lab")
        self.chname_btn = QtWidgets.QPushButton(self.chnamebord)
        self.chname_btn.setGeometry(QtCore.QRect(420, 20, 121, 31))
        self.chname_btn.setObjectName("chname_btn")
        self.tojpgbord = QtWidgets.QGroupBox(self.centralwidget)
        self.tojpgbord.setGeometry(QtCore.QRect(20, 150, 561, 61))
        self.tojpgbord.setObjectName("tojpgbord")
        self.tojpg_lab = QtWidgets.QLineEdit(self.tojpgbord)
        self.tojpg_lab.setGeometry(QtCore.QRect(10, 20, 391, 31))
        self.tojpg_lab.setObjectName("tojpg_lab")
        self.tojpg_btn = QtWidgets.QPushButton(self.tojpgbord)
        self.tojpg_btn.setGeometry(QtCore.QRect(420, 20, 121, 31))
        self.tojpg_btn.setObjectName("tojpg_btn")
        self.statusbord = QtWidgets.QGroupBox(self.centralwidget)
        self.statusbord.setGeometry(QtCore.QRect(230, 220, 351, 221))
        self.statusbord.setObjectName("statusbord")
        self.status_lab = QtWidgets.QTextBrowser(self.statusbord)
        self.status_lab.setGeometry(QtCore.QRect(5, 21, 341, 191))
        self.status_lab.setObjectName("status_lab")
        self.settingbord = QtWidgets.QGroupBox(self.centralwidget)
        self.settingbord.setGeometry(QtCore.QRect(20, 220, 201, 221))
        self.settingbord.setObjectName("settingbord")
        self.progressBar = QtWidgets.QProgressBar(self.settingbord)
        self.progressBar.setGeometry(QtCore.QRect(10, 170, 181, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.setting_lab = QtWidgets.QLineEdit(self.settingbord)
        self.setting_lab.setGeometry(QtCore.QRect(10, 50, 181, 31))
        self.setting_lab.setObjectName("setting_lab")
        self.setting_txt = QtWidgets.QLabel(self.settingbord)
        self.setting_txt.setGeometry(QtCore.QRect(20, 20, 171, 21))
        self.setting_txt.setObjectName("setting_txt")
        self.process_txt = QtWidgets.QLabel(self.settingbord)
        self.process_txt.setGeometry(QtCore.QRect(20, 135, 161, 21))
        self.process_txt.setObjectName("process_txt")
        self.clear_btn = QtWidgets.QPushButton(self.settingbord)
        self.clear_btn.setGeometry(QtCore.QRect(90, 90, 93, 28))
        self.clear_btn.setObjectName("clear_btn")
        self.Clear_lab = QtWidgets.QLabel(self.settingbord)
        self.Clear_lab.setGeometry(QtCore.QRect(10, 94, 71, 21))
        self.Clear_lab.setObjectName("Clear_lab")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.downloadbord.setTitle(_translate("MainWindow", "Download_Youtube Video_URL"))
        self.download_btn.setText(_translate("MainWindow", "Download"))
        self.chnamebord.setTitle(_translate("MainWindow", "Change Video Name "))
        self.chname_btn.setText(_translate("MainWindow", "Change"))
        self.tojpgbord.setTitle(_translate("MainWindow", "Video to Jpg_Input Video File Name"))
        self.tojpg_btn.setText(_translate("MainWindow", "Video_to_JPG"))
        self.statusbord.setTitle(_translate("MainWindow", "Log"))
        self.settingbord.setTitle(_translate("MainWindow", "Frame_Setting"))
        self.setting_txt.setText(_translate("MainWindow", "Input Frame Value"))
        self.process_txt.setText(_translate("MainWindow", "Download progress"))
        self.clear_btn.setText(_translate("MainWindow", "Clear"))
        self.Clear_lab.setText(_translate("MainWindow", "Clear Log"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
